// This file was generated by Prisma
import "dotenv/config";
import dotenv from "dotenv";
import path from "path";
import { defineConfig } from "prisma/config";

// Load .env.local first (for local development overrides)
dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });
// Then load .env (for defaults)
dotenv.config({ path: path.resolve(process.cwd(), ".env") });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
